### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by okpatil4u** [BuJo/goneo#1]
Any plans to add a tutorial ?

**Comment by BuJo** [comment]
You just want to test it out?

Building:

```
go build github.com/BuJo/goneo/cmd/goneo
```

Running the program with a few generated nodes in the in-memory-db:

```
./goneo -size universe
```

Running cypher to search for some labelled nodes:

```
curl -F 'gocy=match (t:Tag) RETURN t.tag AS tag' localhost:7474/table
```

The web interface can also render out the db as graphviz format via `/graphviz` (which also understands form field gocy with a search query).

That's about it basically, tell me if that worked for you, you're correct something along those lines could be in the README.  Hope that helps to understand this little pet project. :D

**Comment by okpatil4u** [comment]
@BuJo Thank you so much for the quick reply. I was wondering how would you check subgraph isomorphism given a target and query graph. It's still not so straightforward in databases such as Neo4j and Dgraph.

**Comment by BuJo** [comment]
Have you had a look at the litarture I pasted at the end of the README?  Those were the papers I read while trying to implement the cypher part of goneo.

This was my idea:  create a graph out of the cypher query, match that subgraph to the complete graph.  I have no idea if other graph databases do it like that (probably much much more performant.. I don't even have any form of indices etc).

So a cypher query like `match (a)-[:c]->(b) return b` would be a graph consisting of two nodes having a relationship.  This subgraph will be searched within the full graph via VF2.  If I remember correctly, it just choosing a start node in both graphs, and iteratively going through the net matching the neighbours.

So basiclly the subgraph isomorphism in this program is an implementation detail of the query language.  But it's a fun one.
